### ISSUE TITLE
commands list minor bug

### ISSUE THREAD

**Issue by dmitriyK1** [kennethreitz/legit#210]
There is a following bug when running legit without any parameters:

<img src="http://image.prntscr.com/image/a57b0c27ed39446ca6fd417f9779b4d0.png"/>

**Comment by weakish** [comment]
Which version do you use?
I have tested with the `develop` branch, and there is no duplicate `sync` entries in help message.

`Unknown command output` is not accurate
(either not considering `legit` without arguments not an error,
either report `missing command`).
This has been fixed in fab5c8f (not considering as an error).
