### ISSUE TITLE
A little bit of bash to make legit and hub work together. Enjoy.

### ISSUE THREAD

**Issue by kura** [kennethreitz/legit#219]
```
alias git='hub'
git() {
  case $@ in
    undo|sy|sync|sw|switch|pub|publish|unp|unpublish|rs|resync|branches)
      cmd='legit'
      ;;
    *)
      cmd='git'
      ;;
  esac
  command "$cmd" "$@"
}
```

Please note, this won't work with the legit completions. Hub completions or Git completions will continue you to work, and you can just combine the legit completions with the existing git/hub ones.

One way you can cheat with the completions is just to define them in `.gitconfig`, this will automatically add the completions to git or hub.

```
[alias]
  branches = branches
  undo = undo
  sync = sync
  sy = sync
  resync = resync
  rs = resync
  switch = switch
  sw = switch
  publish = publish
  pub = publish
  unpublish = unpublish
  unp = unpublish
```

**Comment by weakish** [comment]
I am not familiar with shell scripting.
What is the shell function used for? 

`legit install` installs alias for git.

And `hub` should call git if it encounters an unknown command?

Thus `hub` and `legit` should work together out of the box
except for naming conflicts,
for example, both `hub` and `legit`  use `sync`.

**Comment by kura** [comment]
@weakish hub is https://hub.github.com which improves upon the git CLI by adding functionality that interacts with GitHub itself. While you can use legit and hub together, both of them extend on the `git` command. Therefore they can't work together. My little bit of script allows you to use the functionality of both while basically still aliasing them as `git`.

For example, hub extends on the git CLI and adds a new function called `create`, to call create you can either use:

```git create
hub create```

Legit on the other hand also provides additional functions, for example `undo`:

```git undo
legit undo```

But, if you alias git to hub, you cannot use `git undo`, or if you alias git to legit you can't use `git create`. My code is a little wrapper so you can. That's all. :)

**Comment by weakish** [comment]
@kura 

> if you alias git to hub, you cannot use `git undo`,
> or if you alias git to legit you can't use `git create`.

There are two types of aliases can be used.

1. shell aliases
2. git own aliases

Thus:

- If both program A and B uses 2, then both commands from A and B can be used.
- If one of A and B uses 1, the other uses 2, then both commands from A and B can be used, too.
- But A and B cannot both use 1.

For legit and hub, hub can use 1, and legit can use 2,
and both `git undo` and `git create` will work.

hub cannot use 2 since git does not support delegate its built-in command to external programs.
If hub uses 2, then `git create` will call `hub create`, but `git clone user/repo` does not work.

On the other side, if legit command does not uses `legit branches` but use `legit branch`,
then to call legit via `git branch`, legit need to be aliased in the shell level, just like hub.

Thus I guess:

suppose you have already run `legit install` once, then just

```sh
alias git='hub'
```

in shell startup profile will allow both `git undo` and `git create` to work.

However, since both hub and legit uses the command name `sync`,
then `git sync` will call `hub sync`, not `legit sync`.

If you want to use `legit sync` on calling `git sync`:

```sh
git() {
  case "$1" in
    sync)
      cmd='legit'
      ;;
    *)
      cmd='hub'
      ;;
  esac
  "$cmd" "$@"
}
```

I am not familiar with shell syntax,
I checked bash manual and it seems first alias hub to git,
taken the git name,
then using `command` to call the alias instead of the `git` function itself is unnecessary.
Also it is clearer to write `$1` instead of `$@` without quoting.
And I guess `case $@ in` works because values after space inside `$@` is discarded by shell?

Also I am not sure if `hub` has other conflicts in naming with legit.
However, if there is, and if legit should take priority, then it is easy to add a command.

I have not tested the above code since I does not have `hub` installed on the machine.
Thus there may be mistakes in the code.

**Comment by kura** [comment]
Look, this wasn't a pull request or a feature request or anything. I saw people had asked about using legit and hub together, and so I wrote a little wrapper to do it.

$1 won't work, since it means first argument, meaning `git push origin master` will become `git push`.

Legit and hub don't have any conflicts, I tested the code and use it myself.

Git aliases also won't work on their own, since they call whatever is classified as the git command. So adding an alias for legit and aliasing git to hub will simply not work, you'll be told the command is invalid.

**Comment by weakish** [comment]
> $1 won't work, since it means first argument, meaning git push origin master will become git push.

I thought here only the first argument is interested,
the remaining arguments will still be available in `"$cmd" "$@"`.

>  So adding an alias for legit and aliasing git to hub will simply not work

This works on my machine (debian linux):

```sh
legit install
alias git=hub
```
